# Generated by Django 3.2.4 on 2023-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('profile_image', models.CharField(max_length=255, null=True)),
                ('call_type', models.CharField(max_length=255, null=True)),
                ('muted', models.BooleanField()),
                ('video_disabled', models.BooleanField()),
                ('datetime', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_calls', models.ManyToManyField(to='livestream.ActiveCall')),
            ],
        ),
    ]
